import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';

/**
 * The pasteable bundle is a build artifact that ships in the repo, so it can
 * drift from the source it was built from. This notices.
 */
const bundle = readFileSync(new URL('../worker/paste-into-dashboard.js', import.meta.url), 'utf8');

describe('the file you paste into the Cloudflare dashboard', () => {
  it('is one self-contained module', () => {
    expect(bundle).not.toMatch(/^import .* from ['"]\.\//m);
    expect(bundle).toContain('export {');
  });

  it('carries the rules, not just the entry point', () => {
    expect(bundle).toContain('that handle is taken');
    expect(bundle).toContain('only whoever started the crew can do that');
    expect(bundle).toContain('crew is full');
    expect(bundle).toContain('summary too large');
  });

  // The two that a stale paste would break most quietly.
  it('carries the account rules a stale copy would lose', () => {
    expect(bundle).toContain('too many attempts');
    expect(bundle).toContain('salt-secret');
  });

  it('still hashes secrets rather than storing them', () => {
    expect(bundle).toContain('SHA-256');
  });

  it('says it is generated, so nobody edits it by hand', () => {
    expect(bundle.split('\n')[0]).toContain('Generated by worker/build.mjs');
  });
});
