/**
 * Bundle the worker into one file, for pasting into the Cloudflare dashboard.
 *
 * `wrangler deploy` does not need this — it bundles the TypeScript itself.
 * This exists only for deploying without a terminal.
 */

import { build } from 'esbuild';

await build({
  entryPoints: [new URL('src/index.ts', import.meta.url).pathname],
  outfile: new URL('paste-into-dashboard.js', import.meta.url).pathname,
  bundle: true,
  format: 'esm',
  target: 'es2022',
  banner: {
    js: '// Generated by worker/build.mjs — edit worker/src/*.ts and rebuild, not this file.\n',
  },
});

console.log('wrote worker/paste-into-dashboard.js');
